FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci --legacy-peer-deps

COPY frontend/ .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

RUN apk add --no-cache curl

COPY --from=builder /app/dist ./dist

USER node

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
