FROM mongo:7.0-jammy

RUN useradd -m -u 1000 mongouser && \
    mkdir -p /data/db /data/configdb && \
    chown -R mongouser:mongouser /data/db /data/configdb

COPY ./dump /docker-entrypoint-initdb.d/dump/
COPY ./restore.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/restore.sh && \
    chown -R mongouser:mongouser /docker-entrypoint-initdb.d

USER mongouser

EXPOSE 27017

CMD ["mongod", "--quiet", "--logpath", "/dev/null"]
